sudo: required

services:
  - docker

before_install:
  - docker build -t sarindufit/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sarindufit/react-test npm test

after_success:
  - docker build -t sarindufit/multi-client ./client
  - docker build -t sarindufit/multi-server ./server
  - docker build -t sarindufit/multi-worker ./worker
  - docker build -t sarindufit/multi-nginx ./nginx  
  #Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to the docker hub
  - docker push sarindufit/multi-client
  - docker push sarindufit/multi-server
  - docker push sarindufit/multi-worker
  - docker push sarindufit/multi-nginx
